# Generated by Django 2.1.6 on 2019-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190212_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
