# Generated by Django 2.1.6 on 2019-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190212_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_summary',
            field=models.TextField(blank=True),
        ),
    ]
