# Generated by Django 2.1.6 on 2019-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
